version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: mohammedashiqu/myapp
    steps:
      - run: echo "Hi I'm on a Container Runner!"
  push:
    docker:
      - image: cimg/base:current
    resource_class: mohammedashiqu/myapp
    steps:
      - run: echo "Hi push"
  deploy:
    docker:
      - image: cimg/base:current
    resource_class: mohammedashiqu/myapp
    steps:
      - run: echo "Hi deploy"
workflows:
  build-workflow:
    jobs:
      - build
      - push:
          requires:
            - build
      - deploy:
          requires:
            - push
