version: 2.1

jobs:
  test:
    docker:
      - image: cimg/aws:2023.12
    steps:
      - run:
          name: Run Test
          command: echo "Running tests..."

  build:
    docker:
      - image: cimg/aws:2023.12
    steps:
      - run:
          name: Build Project
          command: echo "Building project..."

  deploy:
    docker:
      - image: cimg/aws:2023.12
    steps:
      - run:
          name: Deploy Project
          command: echo "Deploying project..."

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
